tic
clear all;
close all;
clc;
fs=15;
x1=load('Noisy1.dat');
averagex1=sum(x1)/length(x1);
ax=gca;
ax.YAxis.Exponent=3;

x1=x1-averagex1;
x2=load('Noisy2.dat');
averagex2=sum(x2)/length(x2);
x2=x2-averagex2;
x3=load('Noisy3.dat');
averagex3=sum(x3)/length(x3);
x3=x3-averagex3;
x4=load('Noisy4.dat');
averagex4=sum(x4)/length(x4);
x4=x4-averagex4;
x5=load('Noisy5.dat');
averagex5=sum(x5)/length(x5);
x5=x5-averagex5;
x6=load('Good1.dat');
averagex6=sum(x6)/length(x6);
x6=x6-averagex6;
x7=load('Noisy6.dat');
averagex7=sum(x7)/length(x7);
x7=x7-averagex7;
x8=load('Noisy7.dat');
averagex8=sum(x8)/length(x8);
x8=x8-averagex8;
x9=load('Noisy8.dat');
averagex9=sum(x9)/length(x9);
x9=x9-averagex9;
x10=load('Noisy9.dat');
averagex10=sum(x10)/length(x10);
x10=x10-averagex10;
x11=load('Noisy10.dat');
averagex11=sum(x11)/length(x11);
x11=x11-averagex11;
x12=load('Good2.dat');
averagex12=sum(x12)/length(x12);
x12=x12-averagex12;
x13=load('Noisy11.dat');
averagex13=sum(x13)/length(x13);
x13=x13-averagex13;
x14=load('Noisy12.dat');
averagex14=sum(x14)/length(x14);
x14=x14-averagex14;
x15=load('Noisy13.dat');
averagex15=sum(x15)/length(x15);
x15=x15-averagex15;
x16=load('Noisy14.dat');
averagex16=sum(x16)/length(x16);
x16=x16-averagex16;
x17=load('Noisy15.dat');
averagex17=sum(x17)/length(x17);
x17=x17-averagex17;
x18=load('Good3.dat');
averagex18=sum(x18)/length(x18);
x18=x18-averagex18;
x19=load('Noisy16.dat');
averagex19=sum(x19)/length(x19);
x19=x19-averagex19;
x20=load('Noisy17.dat');
averagex20=sum(x20)/length(x20);
x20=x20-averagex20;
x21=load('Noisy18.dat');
averagex21=sum(x21)/length(x21);
x21=x21-averagex21;
x22=load('Noisy19.dat');
averagex22=sum(x22)/length(x22);
x22=x22-averagex22;
x23=load('Noisy20.dat');
averagex23=sum(x23)/length(x23);
x23=x23-averagex23;
x24=load('Good4.dat');
averagex24=sum(x24)/length(x24);
x24=x24-averagex24;
Length=length(x1)
   t=0:1/fs:(Length-1)/fs;
figure
    subplot(461);
    plot(t,x1,'k');
         ax=gca;
    ax.YAxis.Exponent=4;
%     set(gca,'FontName','Times New Roman','FontSize',9);
   axis([0 length(x1)/fs -max(x1)*1.1 max(x1)*1.1]);
%   xlabel('Time(s)');
    ylabel('Amplitude');
  subplot(462);
    plot(t,x2,'k')
%     set(gca,'FontName','Times New Roman','FontSize',9);
   axis([0 length(x2)/fs -max(x2)*1.1 max(x2)*1.1]);
%   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(463);
    plot(t,x3,'k')
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x3)/fs -max(x3)*1.1 max(x3)*1.1]);
%   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(464);
    plot(t,x4,'k')
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x4)/fs -max(x4)*1.1 max(x4)*1.1]);
%   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(465);
    plot(t,x5,'k')
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x5)/fs -max(x5)*1.1 max(x5)*1.1]);
%   xlabel('Time(s)');
%     ylabel('Amplitude');
  subplot(466);
    plot(t,x6,'r');
%     ax=gca;
%     ax.YAxis.Exponent=3;
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x6)/fs -max(x6)*1.1 max(x6)*1.1]);
%   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(467);
    plot(t,x7,'k')
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x7)/fs -max(x7)*1.1 max(x7)*1.1]);
%   xlabel('Time(s)');
  ylabel('Amplitude');
  subplot(468);
    plot(t,x8,'k')
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x8)/fs -max(x8)*1.1 max(x8)*1.1]);
%   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(469);
    plot(t,x9,'k')
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x9)/fs -max(x9)*1.1 max(x9)*1.1]);
%   xlabel('Time(s)');
%     ylabel('Amplitude');
  subplot(4,6,10);
    plot(t,x10,'k')
   
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x10)/fs -max(x10)*1.1 max(x10)*1.1]);
%   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(4,6,11);
    plot(t,x11,'k')
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x11)/fs -max(x11)*1.1 max(x11)*1.1]);
%   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(4,6,12);
    plot(t,x12,'r');
%      ax=gca;
%     ax.YAxis.Exponent=3;
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x12)/fs -max(x12)*1.1 max(x12)*1.1]);
%   xlabel('Time(s)');
%    ylabel('Amplitude');
  subplot(4,6,13);
    plot(t,x13,'k');
  
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x13)/fs -max(x13)*1.1 max(x13)*1.1]);
%     xlabel('Time(s)');
     ylabel('Amplitude');
  subplot(4,6,14);
    plot(t,x14,'k');
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x14)/fs -max(x14)*1.1 max(x14)*1.1]);
%     xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(4,6,15);
    plot(t,x15,'k');
%     ax=gca;
%     ax.YAxis.Exponent=3;
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x15)/fs -max(x15)*1.1 max(x15)*1.1]);
%     xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(4,6,16);
    plot(t,x16,'k');
%     ax=gca;
%     ax.YAxis.Exponent=3;
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x16)/fs -max(x16)*1.1 max(x16)*1.1]);
%     xlabel('Time(s)');
%   ylabel('Amplitude');
subplot(4,6,17);
    plot(t,x17,'k')
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x7)/fs -max(x7)*1.1 max(x7)*1.1]);
%   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(4,6,18);
    plot(t,x18,'r');
%     ax=gca;
%     ax.YAxis.Exponent=3;
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x8)/fs -max(x8)*1.1 max(x8)*1.1]);
%   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(4,6,19);
    plot(t,x19,'k')
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x9)/fs -max(x9)*1.1 max(x9)*1.1]);
   xlabel('Time(s)');
    ylabel('Amplitude');
  subplot(4,6,20);
    plot(t,x20,'k')
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x10)/fs -max(x10)*1.1 max(x10)*1.1]);
   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(4,6,21);
    plot(t,x21,'k')
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x11)/fs -max(x11)*1.1 max(x11)*1.1]);
   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(4,6,22);
    plot(t,x22,'k');
      ax=gca;
    ax.YAxis.Exponent=4;
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x12)/fs -max(x12)*1.1 max(x12)*1.1]);
   xlabel('Time(s)');
%   ylabel('Amplitude');
  subplot(4,6,23);
    plot(t,x23,'k');
    ax=gca;
    ax.YAxis.Exponent=4;

    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x13)/fs -max(x13)*1.1 max(x13)*1.1]);
    xlabel('Time(s)');
%     ylabel('Amplitude');
  subplot(4,6,24);
    plot(t,x24,'r');
%     ax=gca;
%     ax.YAxis.Exponent=3;
    set(gca,'FontName','Times New Roman','FontSize',9);
%   axis([0 length(x14)/fs -max(x14)*1.1 max(x14)*1.1]);
    xlabel('Time(s)');
%   ylabel('Amplitude');
  
%   ylabel('Amplitude');
 toc;